// Port of org.grobid.core.sax.PDFALTOSaxHandler.
// Upstream: grobid-core/src/main/java/org/grobid/core/sax/PDFALTOSaxHandler.java
//
// SAX parser for XML ALTO representation of fixed layout documents.
// Typographical and layout information are defined at token level, with
// line and block structures.
//
// This parser supports:
//  - pdfalto output from PDF
//
// Expected coverage includes ALTO files generated by OCR (e.g. ABBYY) and
// ALTO files generated from docx files.
//
// TBD: character-level ALTO files

import type { Analyzer } from "../analyzers/analyzer.js";
import { GrobidAnalyzer } from "../analyzers/grobid-analyzer.js";
import type { Document } from "../document/document.js";
import { Block } from "../layout/block.js";
import { BoundingBox } from "../layout/bounding-box.js";
import { GraphicObject } from "../layout/graphic-object.js";
import { GraphicObjectType } from "../layout/graphic-object-type.js";
import { LayoutToken } from "../layout/layout-token.js";
import { Page } from "../layout/page.js";
import { TextUtilities } from "../utilities/text-utilities.js";
import { UnicodeUtil } from "../utilities/unicode-util.js";
import { getLogger } from "../utilities/logger.js";
import { parseSax, type SaxAttributes, type SaxHandler } from "./sax-walker.js";

const LOGGER = getLogger("PDFALTOSaxHandler");

/**
 * Helper class for per-font-id text styling captured during parsing.
 *
 * Upstream TextStyle class defined at line 650-747 of PDFALTOSaxHandler.java.
 */
export class TextStyle {
  // Upstream line 652-666.
  private fontSize: number = 0.0;
  private fontName: string | null = null;
  private fontColor: string | null = null;

  private bold: boolean = false;
  private italic: boolean = false;

  private subscript: boolean = false;
  private superscript: boolean = false;

  // not used attributes
  private proportional: boolean = false;
  private serif: boolean = false;

  // NOTE: upstream line 666 — `//private boolean rotation = false;` (commented-out).

  getFontSize(): number { return this.fontSize; }
  setFontSize(fontSize: number): void { this.fontSize = fontSize; }
  getFontName(): string | null { return this.fontName; }
  setFontName(fontName: string | null): void { this.fontName = fontName; }
  getFontColor(): string | null { return this.fontColor; }
  setFontColor(fontColor: string | null): void { this.fontColor = fontColor; }
  isBold(): boolean { return this.bold; }
  setBold(bold: boolean): void { this.bold = bold; }
  isItalic(): boolean { return this.italic; }
  setItalic(italic: boolean): void { this.italic = italic; }
  // NOTE: upstream lines 708-714 — commented-out rotation getter/setter.
  isProportional(): boolean { return this.proportional; }
  setProportional(proportional: boolean): void { this.proportional = proportional; }
  isSerif(): boolean { return this.serif; }
  setSerif(serif: boolean): void { this.serif = serif; }
  isSubscript(): boolean { return this.subscript; }
  setSubscript(script: boolean): void { this.subscript = script; }
  isSuperscript(): boolean { return this.superscript; }
  setSuperscript(script: boolean): void { this.superscript = script; }
}

/**
 * Upstream PDFALTOSaxHandler.java line 35-647.
 */
export class PDFALTOSaxHandler implements SaxHandler {
  static readonly LOGGER = LOGGER;

  // Upstream line 38.
  private accumulator: string[] = [];

  // Upstream line 40-50.
  private previousToken: string | null = null;
  private previousTok: LayoutToken | null = null;
  private currentX: number = 0.0;
  private currentY: number = 0.0;
  private currentWidth: number = 0.0;
  private currentHeight: number = 0.0;
  private block: Block | null = null;
  private nbTokens: number = 0;
  private images: GraphicObject[];
  private textStyles: Map<string, TextStyle> = new Map<string, TextStyle>();
  private currentRotation: boolean = false;

  // Upstream line 52.
  private tokenizations: LayoutToken[];

  // Upstream line 54.
  private doc: Document;

  // Upstream line 57.
  private currentPage: number = 0;
  // Upstream line 58.
  private page: Page | null = null;
  // Upstream line 59.
  private analyzer: Analyzer = GrobidAnalyzer.getInstance();

  // Upstream line 61.
  private currentOffset: number = 0;

  // Upstream line 63-67.
  constructor(d: Document, im: GraphicObject[]) {
    this.doc = d;
    this.images = im;
    this.tokenizations = [];
  }

  /** Drive the parser from an XML string. */
  parse(xml: string): void {
    parseSax(this, xml);
  }

  // Upstream line 69-71.
  setAnalyzer(analyzer: Analyzer): void {
    this.analyzer = analyzer;
  }

  // Upstream line 73-75.
  getAnalyzer(): Analyzer {
    return this.analyzer;
  }

  // Upstream line 77-91.
  private addToken(layoutToken: LayoutToken): void {
    layoutToken.setOffset(this.currentOffset);
    this.currentOffset += (layoutToken.getText() ?? "").length;
    this.tokenizations.push(layoutToken);
    if (this.doc.getBlocks() === null) {
      layoutToken.setBlockPtr(0);
    } else {
      layoutToken.setBlockPtr(this.doc.getBlocks().length);
    }
    if (this.block === null) {
      LOGGER.info("addToken called with null block object: " + layoutToken.toString());
    } else {
      this.block.addToken(layoutToken);
    }
  }

  // Upstream line 93-102.
  private addBlock(block: Block | null): void {
    if (block === null) LOGGER.info("addBlock called with null block object");

    if (block !== null && !block.isNull() && block.getStartToken() !== block.getEndToken()) {
      block.setPage(this.page!);
      this.doc.addBlock(block);
      this.page!.addBlock(block);
    }
  }

  // Upstream line 104-106.
  getTokenization(): LayoutToken[] {
    return this.tokenizations;
  }

  // Upstream line 108-110.
  characters(ch: string, _start: number, _length: number): void {
    this.accumulator.push(ch);
  }

  // Upstream line 112-123.
  trimAndNormaliseText(content: string): string {
    let res = content.trim();
    // NOTE: upstream lines 114-119 — commented-out NO-BREAK SPACE handling.
    res = UnicodeUtil.normaliseText(res) ?? "";
    return res.trim();
  }

  // Upstream line 125-189.
  endElement(_uri: string, _localName: string, qName: string): void {
    if (qName === "TextLine") {
      const token = new LayoutToken();
      token.setText("\n");
      token.setPage(this.currentPage);
      this.nbTokens++;
      this.accumulator = [];
      this.addToken(token);
    } else if (qName === "Description") {
      this.accumulator = [];
    } else if (qName === "String") {
      this.accumulator = [];
    } else if (qName === "Page") {
      // page marker are useful to detect headers (same first line(s) appearing on each page)
      if (this.block !== null) {
        const localTok = new LayoutToken("\n");
        localTok.setPage(this.currentPage);
        this.addToken(localTok);
        this.addBlock(this.block);
      }
      this.nbTokens = 0;
      this.doc.addPage(this.page!);
    } else if (qName === "TextBlock") {
      const localTok = new LayoutToken("\n");
      localTok.setPage(this.currentPage);
      this.addToken(localTok);

      // NOTE: upstream lines 156-158 — commented out width/height setters.

      this.addBlock(this.block);
      this.nbTokens = 0;
      this.block = null;
    } else if (qName === "Illustration") {
      // this is normally the bitmap images and vector graphics
      // such vector graphics are applied to the whole page, so there is no x,y coordinates available
      // in the xml - to get them we will need to parse the .vec files
      if (this.block !== null) {
        this.addBlock(this.block);
      }
      // NOTE: upstream lines 170-171 — commented out `block = new Block(); block.setStartToken(...);`
      const imagePos = this.images.length - 1;
      // NOTE: upstream lines 173-182 — multiple commented-out blocks preserved.
      this.images[imagePos]!.setStartPosition(this.tokenizations.length);
      this.images[imagePos]!.setEndPosition(this.tokenizations.length);
      this.images[imagePos]!.setPage(this.currentPage);
      // NOTE: upstream line 186 — `//addBlock(block);` (commented-out).
      this.nbTokens = 0;
    }
  }

  // Upstream line 191-193.
  endDocument(): void {
    this.doc.setImages(this.images);
  }

  // Upstream line 195-646.
  startElement(_namespaceURI: string, _localName: string, qName: string, atts: SaxAttributes): void {
    if (qName === "Page") {
      const length = atts.getLength();
      this.currentPage++;
      this.page = new Page(this.currentPage);
      for (let i = 0; i < length; i++) {
        const name = atts.getQName(i);
        const value = atts.getValue(i);
        if (name !== null && value !== null) {
          if (name === "WIDTH") {
            let width = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid WIDTH value: " + value);
            } else {
              width = parsed;
            }
            this.page.setWidth(width);
          } else if (name === "HEIGHT") {
            let height = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid HEIGHT value: " + value);
            } else {
              height = parsed;
            }
            this.page.setHeight(height);
          }
        }
      }
    } else if (qName === "PrintSpace") {
      const length = atts.getLength();
      for (let i = 0; i < length; i++) {
        const name = atts.getQName(i);
        const value = atts.getValue(i);
        if (name !== null && value !== null) {
          switch (name) {
            case "HPOS": {
              let x = 0.0;
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid HPOS value: " + value);
              } else {
                x = parsed;
              }
              if (x !== this.currentX && x !== 0.0) {
                this.currentX = Math.abs(x);
              }
              break;
            }
            case "VPOS": {
              let y = 0.0;
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid VPOS value: " + value);
              } else {
                y = parsed;
              }
              if (y !== this.currentY && y !== 0.0) {
                this.currentY = Math.abs(y);
              }
              break;
            }
            case "WIDTH": {
              let width = 0.0;
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid WIDTH value: " + value);
              } else {
                width = parsed;
              }
              if (width !== this.currentWidth && width !== 0.0) {
                this.currentWidth = Math.abs(width);
              }
              break;
            }
            case "HEIGHT": {
              let height = 0.0;
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid HEIGHT value: " + value);
              } else {
                height = parsed;
              }
              if (height !== this.currentHeight && height !== 0.0) {
                this.currentHeight = Math.abs(height);
              }
              break;
            }
          }
        }
      }
    } else if (qName === "TextBlock") {
      this.block = new Block();
      this.nbTokens = 0;
      this.block.setStartToken(this.tokenizations.length);
    } else if (qName === "Illustration") {
      const length = atts.getLength();
      const image = new GraphicObject();
      let x = 0;
      let y = 0;
      let width = 0;
      let height = 0;
      for (let i = 0; i < length; i++) {
        const name = atts.getQName(i);
        const value = atts.getValue(i);
        if (name !== null && value !== null) {
          switch (name) {
            case "FILEID":
              image.setFilePath(value);
              if (value.includes(".svg")) {
                image.setType(GraphicObjectType.VECTOR);
              } else {
                image.setType(GraphicObjectType.BITMAP);
              }
              break;
            case "HPOS": {
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid HPOS value: " + value);
              } else {
                x = parsed;
              }
              break;
            }
            case "VPOS": {
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid VPOS value: " + value);
              } else {
                y = parsed;
              }
              break;
            }
            case "WIDTH": {
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid WIDTH value: " + value);
              } else {
                width = parsed;
              }
              break;
            }
            case "HEIGHT": {
              const parsed = parseFloat(value);
              if (Number.isNaN(parsed)) {
                LOGGER.warn("Invalid HEIGHT value: " + value);
              } else {
                height = parsed;
              }
              break;
            }
            case "TYPE":
              if (value === "svg") {
                image.setType(GraphicObjectType.VECTOR);
              } else {
                image.setType(GraphicObjectType.BITMAP);
              }
              break;
          }
        }
      }
      image.setBoundingBox(BoundingBox.fromPointAndDimensions(this.currentPage, x, y, width, height));
      image.setPage(this.currentPage);
      this.images.push(image);
    } else if (qName === "TextLine") {
      // NOTE: upstream lines 354-367 — commented-out attribute-processing block.
      void atts;
    } else if (qName === "String") {
      const length = atts.getLength();
      let content: string | null = null;
      let fontId: string | null = null;
      let textStyle: TextStyle | null = null;
      for (let i = 0; i < length; i++) {
        const name = atts.getQName(i);
        const value = atts.getValue(i);
        if (name !== null && value !== null) {
          if (name === "ID") {
            // upstream: `;` — no-op.
          } else if (name === "CONTENT") {
            content = value;
          } else if (name === "STYLEREFS") {
            fontId = value;
          } else if (name === "rotation") {
            if (value === "0") this.currentRotation = false;
            else this.currentRotation = true;
          } else if (name === "HPOS") {
            let x = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid HPOS value: " + value);
            } else {
              x = parsed;
            }
            if (x !== this.currentX && x !== 0.0) {
              this.currentX = Math.abs(x);
            }
          } else if (name === "VPOS") {
            let y = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid VPOS value: " + value);
            } else {
              y = parsed;
            }
            if (y !== this.currentY && y !== 0.0) {
              this.currentY = Math.abs(y);
            }
          } else if (name === "base") {
            // Upstream parses `base` but doesn't store it — preserved verbatim.
            let base = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid base value: " + value);
            } else {
              base = parsed;
            }
            void base;
          } else if (name === "WIDTH") {
            let width = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid WIDTH value: " + value);
            } else {
              width = parsed;
            }
            if (width !== this.currentWidth && width !== 0.0) {
              this.currentWidth = Math.abs(width);
            }
          } else if (name === "HEIGHT") {
            let height = 0.0;
            const parsed = parseFloat(value);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid HEIGHT value: " + value);
            } else {
              height = parsed;
            }
            if (height !== this.currentHeight && height !== 0.0) {
              this.currentHeight = Math.abs(height);
            }
          }
        }
      }

      // process ligatures
      const tok0 = TextUtilities.clean(this.trimAndNormaliseText(content ?? "")) ?? "";
      textStyle = this.textStyles.get(fontId ?? "") ?? null;

      if (this.block!.getStartToken() === -1) {
        this.block!.setStartToken(this.tokenizations.length);
      }

      if (tok0.length > 0) {
        // NOTE: upstream lines 451-452 — commented out StringTokenizer creation.
        let subTokenizations: string[] = [];
        try {
          // TBD: pass a language object to the tokenize method call
          subTokenizations = this.analyzer.tokenize(tok0);
        } catch {
          LOGGER.debug("Sub-tokenization of pdfalto token has failed.");
        }
        if (subTokenizations.length !== 0) {
          // WARNING: ROUGH APPROXIMATION (but better than the same coords)
          let totalLength = 0;
          for (const t of subTokenizations) {
            totalLength += t.length;
          }
          let prevSubWidth = 0;
          for (const tok of subTokenizations) {
            // WARNING: ROUGH APPROXIMATION (but better than the same coords)
            // Here to get the right subTokWidth should use the content length.
            const subTokWidth = this.currentWidth * (tok.length / totalLength);
            const subTokX = this.currentX + prevSubWidth;
            prevSubWidth += subTokWidth;
            // NOTE: upstream line 481 — `//String tok = st.nextToken();` (commented-out).
            if (tok.length > 0) {
              const token = new LayoutToken();
              token.setPage(this.currentPage);
              token.setText(tok);
              this.addToken(token);

              if (this.currentRotation) {
                // if the text is rotated, it appears that the font size is multiplied
                // by 2? we should have a look at pdf2xml/pdfalto for this
                textStyle!.setFontSize(textStyle!.getFontSize() / 2);
              }

              if (textStyle!.getFontName() !== null) {
                token.setFont(textStyle!.getFontName()!.toLowerCase());
              } else {
                token.setFont("default");
              }
              token.setItalic(textStyle!.isItalic());
              token.setBold(textStyle!.isBold());
              token.setRotation(this.currentRotation);
              token.setPage(this.currentPage);
              token.setColorFont(textStyle!.getFontColor());

              token.setSubscript(textStyle!.isSubscript());
              token.setSuperscript(textStyle!.isSuperscript());

              token.setX(subTokX);
              token.setY(this.currentY);
              token.setWidth(subTokWidth);
              token.setHeight(this.currentHeight);

              // NOTE: upstream lines 513-516 — commented-out token.setX/Y/Width/Height(currentX/Y/Width/Height) overrides.

              token.setFontSize(textStyle!.getFontSize());

              // NOTE: upstream lines 520-523 — commented-out diaresis/accent guard around block.addToken.

              if (this.block!.getFont() === null) {
                if (textStyle!.getFontName() !== null) {
                  this.block!.setFont(textStyle!.getFontName()!.toLowerCase());
                } else {
                  token.setFont("default");
                }
              }
              if (this.nbTokens === 0) {
                this.block!.setItalic(textStyle!.isItalic());
                this.block!.setBold(textStyle!.isBold());
              }
              if (this.block!.getColorFont() === null) {
                this.block!.setColorFont(textStyle!.getFontColor() ?? "");
              }
              // NOTE: upstream lines 538-547 — commented-out block.setX/Y/Width/Height/FontSize() defaults.

              this.previousToken = tok;
              this.previousTok = token;

              this.nbTokens++;
            }
          }
        }
        if (this.tokenizations.length > 0) {
          const justBefore = this.tokenizations[this.tokenizations.length - 1]!.t() ?? "";
          if (!justBefore.endsWith("-")) {
            const localTok = new LayoutToken(" ");
            localTok.setPage(this.currentPage);
            this.addToken(localTok);
          }
        }
      }
      this.block!.setEndToken(this.tokenizations.length);
    } else if (qName === "TextStyle") {
      const length = atts.getLength();
      const textStyle = new TextStyle();
      let fontId: string | null = null;
      for (let i = 0; i < length; i++) {
        const name = atts.getQName(i);
        const value = atts.getValue(i);
        // Upstream uses `StringUtils.isNotBlank` — non-null + non-empty + non-whitespace.
        if (PDFALTOSaxHandler.isNotBlank(name) && PDFALTOSaxHandler.isNotBlank(value)) {
          if (name === "ID") {
            fontId = value;
          } else if (name === "FONTFAMILY") {
            // NOTE: upstream lines 581-587 — commented-out bold/italic detection on FONTFAMILY.
            textStyle.setFontName(value);
          } else if (name === "FONTSIZE") {
            let fontSize = 0.0;
            const parsed = parseFloat(value!);
            if (Number.isNaN(parsed)) {
              LOGGER.warn("Invalid FONTSIZE value: " + value);
            } else {
              fontSize = parsed;
            }
            textStyle.setFontSize(fontSize);
          } else if (name === "FONTSTYLE") {
            // font properties, we are interested by subscript or superscript
            if (PDFALTOSaxHandler.containsIgnoreCase(value!, "subscript")) {
              textStyle.setSubscript(true);
            }
            if (PDFALTOSaxHandler.containsIgnoreCase(value!, "superscript")) {
              textStyle.setSuperscript(true);
            }
            if (PDFALTOSaxHandler.containsIgnoreCase(value!, "bold")) {
              textStyle.setBold(true);
            }
            if (
              PDFALTOSaxHandler.containsIgnoreCase(value!, "italic") ||
              PDFALTOSaxHandler.containsIgnoreCase(value!, "italics")
            ) {
              textStyle.setItalic(true);
            }
          } else if (name === "FONTCOLOR") {
            textStyle.setFontColor(value);
          } else if (name === "FONTTYPE") {
            // value can be empty or a sequence of font properties separated by space, out of these
            // NOTE: upstream lines 621-625 — commented-out `if (value.equals("serif"))` branch.
          }
          // NOTE: upstream lines 627-640 — commented-out FONTWIDTH and rotation branches.
        }
      }
      if (fontId !== null) {
        this.textStyles.set(fontId, textStyle);
      }
    }
  }

  /** `StringUtils.isNotBlank` — non-null + non-empty + at least one non-whitespace char. */
  private static isNotBlank(s: string | null): boolean {
    if (s === null || s === undefined) return false;
    for (let i = 0; i < s.length; i++) {
      const c = s.charCodeAt(i);
      if (c !== 0x20 && c !== 0x09 && c !== 0x0a && c !== 0x0d) return true;
    }
    return false;
  }

  /** `StringUtils.containsIgnoreCase`. */
  private static containsIgnoreCase(haystack: string, needle: string): boolean {
    return haystack.toLowerCase().includes(needle.toLowerCase());
  }
}
